CREATE TABLE `email_captures` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(320) NOT NULL,
	`sessionId` varchar(64) NOT NULL,
	`personaId` int,
	`personaName` varchar(50),
	`source` varchar(50) DEFAULT 'chatbot',
	`captureMethod` varchar(50) DEFAULT 'email_popup',
	`messageCount` int DEFAULT 0,
	`lastDestinationMentioned` varchar(100),
	`lastBudgetMentioned` int,
	`gdprConsent` int NOT NULL DEFAULT 0,
	`consentText` text,
	`tags` text,
	`segment` varchar(50),
	`emailSent` int DEFAULT 0,
	`emailOpened` int DEFAULT 0,
	`emailClicked` int DEFAULT 0,
	`unsubscribed` int DEFAULT 0,
	`capturedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `email_captures_id` PRIMARY KEY(`id`)
);
