/**
 * SEO Destination Data for Country and City Pages
 * 
 * Contains keyword-optimized content, affiliate links, and metadata
 * for all destination landing pages
 */

export interface SEODestination {
  name: string;
  slug: string;
  type: "country" | "city";
  title: string; // SEO page title
  metaDescription: string; // SEO meta description
  h1: string; // Main heading
  h2: string; // Subheading
  description: string; // Main content paragraph
  keywords: string[]; // Target keywords from CSV
  searchVolume: number; // Monthly search volume
  difficulty: number; // SEO difficulty (0-100)
  pelikanUrl: string; // Pelikan.cz affiliate URL
  kiwiUrl: string; // Kiwi.com search URL
  image: string; // Hero image URL
  iataCode?: string; // IATA airport/city code for calendar widget (e.g. "CDG", "LHR")
  latitude?: number; // GPS coordinates for Place schema
  longitude?: number;
  relatedDestinations?: string[]; // Related destination slugs for internal linking
}

// 16 Country Destinations
export const destinationCountries: SEODestination[] = [
  {
    name: "USA",
    slug: "usa",
    type: "country",
    title: "Letenky do USA od 7 490 Kč | New York, Miami, Los Angeles",
    metaDescription: "Nejlevnější letenky do USA z Prahy. New York od 7 490 Kč, Miami od 9 490 Kč. Porovnání cen Pelikan.cz a Kiwi.com. Rezervujte last minute letenky se slevou.",
    h1: "Letenky do USA",
    h2: "Země neomezených možností",
    description: "Spojené státy americké nabízejí nekonečné možnosti pro cestovatele. Od mrakodrapů New Yorku přes slunné pláže Miami až po Hollywood v Los Angeles. Najděte nejlevnější letenky do USA a objevte americký sen.",
    keywords: ["letenky do usa", "letenky usa", "levné letenky usa", "letenky new york", "letenky miami"],
    searchVolume: 8100,
    difficulty: 65,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=US",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/spojene-staty-americke/anytime/no-return/",
    image: "/destinations/usa.jpg",
    latitude: 37.0902,
    longitude: -95.7129,
    relatedDestinations: ["new-york", "miami"],
  },
  {
    name: "Řecko",
    slug: "recko",
    type: "country",
    title: "Letenky do Řecka od 1 791 Kč | Santorini, Kréta, Rhodos",
    metaDescription: "Levné letenky do Řecka z Prahy. Santorini od 1 791 Kč, Kréta, Rhodos. Dovolená s řeckými bohy. Porovnání cen a rezervace online.",
    h1: "Letenky do Řecka",
    h2: "Dovolená s řeckými bohy",
    description: "Řecko je synonymem pro dokonalou dovolenou - bílé domky Santorini, krétské pláže a historické památky Atén. Najděte nejlevnější letenky do Řecka a zažijte středomořský ráj.",
    keywords: ["letenky do řecka", "letenky řecko", "levné letenky řecko", "letenky santorini", "letenky kréta"],
    searchVolume: 6600,
    difficulty: 58,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=GR",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/recko/anytime/no-return/",
    image: "/destinations/greece.jpg",
    latitude: 39.0742,
    longitude: 21.8243,
    relatedDestinations: [],
  },
  {
    name: "Velká Británie",
    slug: "velka-britanie",
    type: "country",
    title: "Letenky do Velké Británie od 733 Kč | Londýn, Edinburgh",
    metaDescription: "Nejlevnější letenky do Velké Británie. Londýn od 733 Kč, Edinburgh, Manchester. Beatles a skotské zámky. Rezervujte online.",
    h1: "Letenky do Velké Británie",
    h2: "Londýn, Beatles a skotské zámky",
    description: "Velká Británie kombinuje královskou historii Londýna, hudební dědictví Beatles v Liverpoolu a drsnou krásu skotských vysočin. Objevte ostrovní království s levnými letenkami.",
    keywords: ["letenky do velké británie", "letenky londýn", "levné letenky anglie", "letenky edinburgh"],
    searchVolume: 5400,
    difficulty: 52,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=GB",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/velka-britanie/anytime/no-return/",
    image: "/destinations/uk.jpg",
    latitude: 55.3781,
    longitude: -3.4360,
    relatedDestinations: ["londyn"],
  },
  {
    name: "Španělsko",
    slug: "spanelsko",
    type: "country",
    title: "Letenky do Španělska od 746 Kč | Barcelona, Madrid, Malaga",
    metaDescription: "Levné letenky do Španělska z Prahy. Barcelona od 746 Kč, Madrid, Malaga. Gaudí, tapas a městské pláže. Porovnání cen.",
    h1: "Letenky do Španělska",
    h2: "Nákonečné pobřeží a metropole",
    description: "Španělsko nabízí perfektní kombinaci kultury, gastronomie a pláží. Od Gaudího architektury v Barceloně přes královský Madrid až po slunnou Malagu. Najděte nejlevnější letenky do Španělska.",
    keywords: ["letenky do španělska", "letenky španělsko", "levné letenky španělsko", "letenky barcelona", "letenky madrid"],
    searchVolume: 9900,
    difficulty: 61,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=ES",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/spanelsko/anytime/no-return/",
    image: "/destinations/spain.jpg",
    latitude: 40.4637,
    longitude: -3.7492,
    relatedDestinations: ["barcelona", "malaga", "palma-de-mallorca"],
  },
  {
    name: "Itálie",
    slug: "italie",
    type: "country",
    title: "Letenky do Itálie od 712 Kč | Řím, Milán, Benátky",
    metaDescription: "Nejlevnější letenky do Itálie. Řím od 712 Kč, Milán, Benátky, Neapol. Památky a excelentní kuchyň. Rezervujte online.",
    h1: "Letenky do Itálie",
    h2: "Památky a excelentní kuchyň",
    description: "Itálie je kolébkou evropské civilizace s nekonečným bohatstvím památek, umění a gastronomie. Od Kolosea v Římě přes módní Milán až po romantické Benátky.",
    keywords: ["letenky do itálie", "letenky itálie", "levné letenky itálie", "letenky řím", "letenky milán"],
    searchVolume: 8100,
    difficulty: 59,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=IT",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/italie/anytime/no-return/",
    image: "/destinations/italy.jpg",
    latitude: 41.8719,
    longitude: 12.5674,
    relatedDestinations: ["rim", "milano", "neapol"],
  },
  {
    name: "SAE (Spojené arabské emiráty)",
    slug: "sae",
    type: "country",
    title: "Letenky do SAE od 5 183 Kč | Dubaj, Abu Dhabi",
    metaDescription: "Levné letenky do SAE. Dubaj od 5 183 Kč, Abu Dhabi. Luxus a mrakodrapy. Porovnání cen Pelikan.cz a Kiwi.com.",
    h1: "Letenky do Spojených arabských emirátů",
    h2: "Dobrodružství a odpočinek na pláži",
    description: "Spojené arabské emiráty představují futuristickou vizi Blízkého východu. Dubaj s nejvyšší budovou světa Burj Khalifa a Abu Dhabi s Velkou mešitou nabízejí luxus a exotiku.",
    keywords: ["letenky do sae", "letenky dubaj", "levné letenky emiráty", "letenky abu dhabi"],
    searchVolume: 4400,
    difficulty: 54,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=AE",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/spojene-arabske-emiraty/anytime/no-return/",
    image: "/destinations/uae.jpg",
    latitude: 23.4241,
    longitude: 53.8478,
    relatedDestinations: ["dubaj", "abu-dhabi"],
  },
  {
    name: "Island",
    slug: "island",
    type: "country",
    title: "Letenky na Island od 1 460 Kč | Reykjavík, Polární záře",
    metaDescription: "Nejlevnější letenky na Island. Reykjavík od 1 460 Kč. Kouzelný ostrov gejzírů, ledovců a polární záře. Rezervujte online.",
    h1: "Letenky na Island",
    h2: "Kouzelný ostrov gejzírů",
    description: "Island je země ohně a ledu - aktivní sopky, mohutné ledovce, horké prameny a magická polární záře. Reykjavík je bránou do této severské pohádky.",
    keywords: ["letenky na island", "letenky island", "levné letenky island", "letenky reykjavík"],
    searchVolume: 3600,
    difficulty: 48,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=IS",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/island/anytime/no-return/",
    image: "/destinations/iceland.jpg",
    latitude: 64.9631,
    longitude: -19.0208,
    relatedDestinations: [],
  },
  {
    name: "Kypr",
    slug: "kypr",
    type: "country",
    title: "Letenky na Kypr od 2 990 Kč | Larnaca, Paphos, Pláže",
    metaDescription: "Levné letenky na Kypr. Larnaca od 2 990 Kč, Paphos. Nádherné písčité pláže a středomořská atmosféra. Porovnání cen.",
    h1: "Letenky na Kypr",
    h2: "Nádherné písčité pláže",
    description: "Kypr je ostrov Afrodity s krásnými plážemi, antickými památkami a vynikající kuchyní. Ideální destinace pro rodinnou dovolenou i romantický výlet.",
    keywords: ["letenky na kypr", "letenky kypr", "levné letenky kypr", "letenky larnaca"],
    searchVolume: 2900,
    difficulty: 45,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=CY",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/kypr/anytime/no-return/",
    image: "/destinations/cyprus.jpg",
    latitude: 35.1264,
    longitude: 33.4299,
    relatedDestinations: [],
  },
  {
    name: "Austrálie",
    slug: "australie",
    type: "country",
    title: "Letenky do Austrálie od 15 990 Kč | Sydney, Melbourne",
    metaDescription: "Nejlevnější letenky do Austrálie. Sydney od 15 990 Kč, Melbourne. Klokani a vřín oceán. Rezervujte online.",
    h1: "Letenky do Austrálie",
    h2: "Klokani a vřín oceán",
    description: "Austrálie je kontinent plný kontrastů - od ikonické Opera House v Sydney přes Velký bariérový útes až po outback. Zažijte dobrodružství na druhém konci světa.",
    keywords: ["letenky do austrálie", "letenky austrálie", "levné letenky austrálie", "letenky sydney"],
    searchVolume: 2400,
    difficulty: 52,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=AU",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/australie/anytime/no-return/",
    image: "/destinations/australia.jpg",
    latitude: -25.2744,
    longitude: 133.7751,
    relatedDestinations: [],
  },
  {
    name: "Dánsko",
    slug: "dansko",
    type: "country",
    title: "Letenky do Dánska od 1 290 Kč | Kodaň, Legoland",
    metaDescription: "Levné letenky do Dánska. Kodaň od 1 290 Kč, Legoland. Země vikingů a Legolandu. Porovnání cen.",
    h1: "Letenky do Dánska",
    h2: "Země vikingů a Legolandu",
    description: "Dánsko je skandinávská pohádka s barevnými domky v Kodani, historií vikingů a slavným Legolandem. Ideální destinace pro rodinný výlet.",
    keywords: ["letenky do dánska", "letenky dánsko", "levné letenky dánsko", "letenky kodaň"],
    searchVolume: 1800,
    difficulty: 42,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=DK",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/dansko/anytime/no-return/",
    image: "/destinations/denmark.jpg",
    latitude: 56.2639,
    longitude: 9.5018,
    relatedDestinations: [],
  },
  {
    name: "Malta",
    slug: "malta",
    type: "country",
    title: "Letenky na Maltu od 1 990 Kč | Valletta, Pláže",
    metaDescription: "Nejlevnější letenky na Maltu. Valletta od 1 990 Kč. Historie a krásné pláže. Rezervujte online.",
    h1: "Letenky na Maltu",
    h2: "Historie a krásné pláže",
    description: "Malta je malý ostrov s velkou historií - od rytířů maltézského řádu přes barokní Vallettu až po tyrkysové laguny. Ideální pro kombinaci kultury a odpočinku.",
    keywords: ["letenky na maltu", "letenky malta", "levné letenky malta", "letenky valletta"],
    searchVolume: 2200,
    difficulty: 44,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=MT",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/malta/anytime/no-return/",
    image: "/destinations/malta.jpg",
    latitude: 35.9375,
    longitude: 14.3754,
    relatedDestinations: [],
  },
  {
    name: "Chorvatsko",
    slug: "chorvatsko",
    type: "country",
    title: "Letenky do Chorvatska od 1 114 Kč | Dubrovník, Split, Zadar",
    metaDescription: "Levné letenky do Chorvatska. Dubrovník od 1 114 Kč, Split, Zadar. Oblíbená dovolenková klasika. Porovnání cen.",
    h1: "Letenky do Chorvatska",
    h2: "Oblíbená dovolenková klasika",
    description: "Chorvatsko je nejoblíbenější letní destinací Čechů - krásné pláže, čisté moře, historická města jako Dubrovník a Split. Najděte nejlevnější letenky do Chorvatska.",
    keywords: ["letenky do chorvatska", "letenky chorvatsko", "levné letenky chorvatsko", "letenky dubrovník"],
    searchVolume: 7200,
    difficulty: 56,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=HR",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/chorvatsko/anytime/no-return/",
    image: "/destinations/croatia.jpg",
    latitude: 45.1,
    longitude: 15.2,
    relatedDestinations: ["zadar"],
  },
  {
    name: "Thajsko",
    slug: "thajsko",
    type: "country",
    title: "Letenky do Thajska od 12 390 Kč | Bangkok, Phuket",
    metaDescription: "Nejlevnější letenky do Thajska. Bangkok od 12 390 Kč, Phuket. Dobrodružství a odpočinek na pláži. Rezervujte online.",
    h1: "Letenky do Thajska",
    h2: "Dobrodružství a odpočinek na pláži",
    description: "Thajsko je země úsměvů s exotickými chrámy, tropickými plážemi a vynikající kuchyní. Od rušného Bangkoku přes ostrovy Phuket a Koh Samui až po historický Chiang Mai.",
    keywords: ["letenky do thajska", "letenky thajsko", "levné letenky thajsko", "letenky bangkok"],
    searchVolume: 8900,
    difficulty: 62,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=TH",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/thajsko/anytime/no-return/",
    image: "/destinations/thailand.jpg",
    latitude: 15.8700,
    longitude: 100.9925,
    relatedDestinations: ["bangkok"],
  },
  {
    name: "Zanzibar",
    slug: "zanzibar",
    type: "country",
    title: "Letenky na Zanzibar od 14 990 Kč | Stone Town, Pláže",
    metaDescription: "Levné letenky na Zanzibar. Stone Town od 14 990 Kč. Dokonalé pláže a bílý písek. Porovnání cen.",
    h1: "Letenky na Zanzibar",
    h2: "Dokonalé pláže a bílý písek",
    description: "Zanzibar je africký ráj s nejkrásnějšími plážemi světa, tyrkysovým mořem a historickým Stone Town. Ideální destinace pro romantickou dovolenou.",
    keywords: ["letenky na zanzibar", "letenky zanzibar", "levné letenky zanzibar"],
    searchVolume: 1600,
    difficulty: 38,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CityTo][]=ZNZ",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/zanzibar/anytime/no-return/",
    image: "/destinations/zanzibar.jpg",
    latitude: -6.1659,
    longitude: 39.2026,
    relatedDestinations: [],
  },
  {
    name: "Mexiko",
    slug: "mexiko",
    type: "country",
    title: "Letenky do Mexika od 10 990 Kč | Cancún, Mexico City",
    metaDescription: "Nejlevnější letenky do Mexika. Cancún od 10 990 Kč, Mexico City. Nádvožná letoviska a bohatá historie. Rezervujte online.",
    h1: "Letenky do Mexika",
    h2: "Nádvožná letoviska a bohatá historie",
    description: "Mexiko kombinuje karibské pláže Cancúnu, mayské pyramidy a živou kulturu Mexico City. Zažijte tequilu, tacos a nezapomenutelnou atmosféru.",
    keywords: ["letenky do mexika", "letenky mexiko", "levné letenky mexiko", "letenky cancún"],
    searchVolume: 3300,
    difficulty: 49,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky?a_aid=levne-letenky&data[CountryTo][]=MX",
    kiwiUrl: "https://www.kiwi.com/cz/search/tiles/letiste-vaclava-havla-praha-praha-cesko/mexiko/anytime/no-return/",
    image: "/destinations/mexico.jpg",
    latitude: 23.6345,
    longitude: -102.5528,
    relatedDestinations: ["cancun"],
  },
  {
    name: "Wellness v Česku a na Slovensku",
    slug: "wellness-cesko-slovensko",
    type: "country",
    title: "Wellness v Česku a na Slovensku | Nejlepší Tipy",
    metaDescription: "Zkuste naše tipy na top pobyty v Česku a na Slovensku. Relaxace, lázně a spa. Porovnání cen.",
    h1: "Nejlepší Wellnessy v Česku a na Slovensku",
    h2: "Zkuste naše tipy na top pobyty",
    description: "Objevte nejlepší wellness hotely a lázně v Česku a na Slovensku. Od Karlových Varů přes Mariánské Lázně až po slovenské Tatry. Relaxace na dosah ruky.",
    keywords: ["wellness česko", "wellness slovensko", "lázně česko", "spa pobyty"],
    searchVolume: 4800,
    difficulty: 51,
    pelikanUrl: "https://www.pelikan.cz/pobyty?a_aid=levne-letenky&data[TypeOfHoliday][]=wellness",
    kiwiUrl: "",
    image: "/destinations/wellness.jpg",
    latitude: 49.8175,
    longitude: 15.4730,
    relatedDestinations: [],
  },
];

// 20 City Destinations
export const destinationCities: SEODestination[] = [
  {
    name: "New York",
    slug: "new-york",
    type: "city",
    title: "Letenky do New Yorku od 7 490 Kč | Big Apple, Manhattan",
    metaDescription: "Nejlevnější letenky do New Yorku z Prahy. Manhattan od 7 490 Kč. Město, které nikdy nespí. Porovnání cen Pelikan.cz a Kiwi.com.",
    h1: "Letenky do New Yorku",
    h2: "Město, které nikdy nespí",
    description: "New York je ikonické město mrakodrapů, Broadway show a Sochy svobody. Od Times Square přes Central Park až po Brooklyn Bridge - zažijte americký sen v Big Apple.",
    keywords: ["letenky new york", "letenky do new yorku", "levné letenky new york", "letenky manhattan"],
    searchVolume: 12100,
    difficulty: 68,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/new-york?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=NYC",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/new-york-city-new-york-united-states/anytime/anytime/?sortBy=price",
    image: "/destinations/newyork.jpg",
    iataCode: "JFK",
    latitude: 40.7128,
    longitude: -74.0060,
    relatedDestinations: ["usa"],
  },
  {
    name: "Londýn",
    slug: "londyn",
    type: "city",
    title: "Letenky do Londýna od 733 Kč | Big Ben, Tower Bridge",
    metaDescription: "Levné letenky do Londýna z Prahy. Big Ben od 733 Kč. Beatles a skotské zámky. Rezervujte online.",
    h1: "Letenky do Londýna",
    h2: "Královské město plné historie",
    description: "Londýn je hlavní město Velké Británie s ikonickým Big Benem, Tower Bridge a Buckinghamským palácem. Objevte královskou historii, muzea světové úrovně a živou kulturní scénu.",
    keywords: ["letenky londýn", "letenky do londýna", "levné letenky londýn", "letenky big ben"],
    searchVolume: 14500,
    difficulty: 71,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/londyn?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=LON",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/london-united-kingdom/anytime/anytime/?sortBy=price",
    image: "/destinations/london.jpg",
    iataCode: "LHR",
    latitude: 51.5074,
    longitude: -0.1278,
    relatedDestinations: ["velka-britanie"],
  },
  {
    name: "Miami",
    slug: "miami",
    type: "city",
    title: "Letenky do Miami od 9 490 Kč | South Beach, Art Deco",
    metaDescription: "Nejlevnější letenky do Miami. South Beach od 9 490 Kč. Slunce, pláže a Art Deco. Porovnání cen.",
    h1: "Letenky do Miami",
    h2: "Slunce, pláže a Art Deco",
    description: "Miami je floridský ráj s nekonečnými plážemi, Art Deco architekturou a živým nočním životem. South Beach, Little Havana a Everglades čekají na objevení.",
    keywords: ["letenky miami", "letenky do miami", "levné letenky miami", "letenky south beach"],
    searchVolume: 5900,
    difficulty: 58,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/miami?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=MIA",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/miami-florida-united-states/anytime/anytime/?sortBy=price",
    image: "/destinations/miami.jpg",
    iataCode: "MIA",
    latitude: 25.7617,
    longitude: -80.1918,
    relatedDestinations: ["usa"],
  },
  {
    name: "Paříž",
    slug: "pariz",
    type: "city",
    title: "Letenky do Paříže od 1 027 Kč | Eiffelova věž, Louvre",
    metaDescription: "Levné letenky do Paříže. Eiffelova věž od 1 027 Kč. Město lásky, umění a gastronomie. Rezervujte online.",
    h1: "Letenky do Paříže",
    h2: "Město lásky, umění a gastronomie",
    description: "Paříž je synonymem pro romantiku - Eiffelova věž, Louvre, Notre-Dame a Montmartre. Zažijte francouzskou kuchyni, víno a nezapomenutelnou atmosféru.",
    keywords: ["letenky paříž", "letenky do paříže", "levné letenky paříž", "letenky eiffelova věž"],
    searchVolume: 11200,
    difficulty: 66,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/pariz?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=PAR",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/paris-france/anytime/anytime/?sortBy=price",
    image: "/destinations/paris.jpg",
    iataCode: "CDG",
    latitude: 48.8566,
    longitude: 2.3522,
    relatedDestinations: [],
  },
  {
    name: "Řím",
    slug: "rim",
    type: "city",
    title: "Letenky do Říma od 712 Kč | Koloseum, Vatikán",
    metaDescription: "Nejlevnější letenky do Říma. Koloseum od 712 Kč. Věčné město plné památek. Porovnání cen.",
    h1: "Letenky do Říma",
    h2: "Věčné město plné památek",
    description: "Řím je kolébka evropské civilizace s Kolosseem, Vatikánem a Fontánou di Trevi. Projděte se po stopách gladiátorů a objevte italskou kuchyni.",
    keywords: ["letenky řím", "letenky do říma", "levné letenky řím", "letenky koloseum"],
    searchVolume: 9800,
    difficulty: 64,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/rim?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=ROM",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/letiste-rim-fiumicino-rim-italie/anytime/anytime/?sortBy=price",
    image: "/destinations/rome.jpg",
    iataCode: "FCO",
    latitude: 41.9028,
    longitude: 12.4964,
    relatedDestinations: ["italie"],
  },
  {
    name: "Barcelona",
    slug: "barcelona",
    type: "city",
    title: "Letenky do Barcelony od 746 Kč | Sagrada Família, Gaudí",
    metaDescription: "Levné letenky do Barcelony. Sagrada Família od 746 Kč. Gaudí, tapas a městské pláže. Rezervujte online.",
    h1: "Letenky do Barcelony",
    h2: "Gaudí, tapas a městské pláže",
    description: "Barcelona je katalánská metropole s unikátní architekturou Antoního Gaudího. Sagrada Família, Park Güell a La Rambla čekají na objevení.",
    keywords: ["letenky barcelona", "letenky do barcelony", "levné letenky barcelona", "letenky sagrada familia"],
    searchVolume: 10500,
    difficulty: 65,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/barcelona?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=BCN",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/barcelona-spain/anytime/anytime/?sortBy=price",
    image: "/destinations/barcelona.jpg",
    iataCode: "BCN",
    latitude: 41.3851,
    longitude: 2.1734,
    relatedDestinations: ["spanelsko"],
  },
  {
    name: "Bangkok",
    slug: "bangkok",
    type: "city",
    title: "Letenky do Bangkoku od 12 390 Kč | Chrámy, Trhy",
    metaDescription: "Nejlevnější letenky do Bangkoku. Chrámy od 12 390 Kč. Exotika, chrámy a pouliční jídlo. Porovnání cen.",
    h1: "Letenky do Bangkoku",
    h2: "Exotika, chrámy a pouliční jídlo",
    description: "Bangkok je rušná thajská metropole s nádher nými chrámy, plovoucími trhy a vynikající street food scénou. Brána do jihovýchodní Asie.",
    keywords: ["letenky bangkok", "letenky do bangkoku", "levné letenky bangkok"],
    searchVolume: 7800,
    difficulty: 61,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/bangkok?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=BKK",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/bangkok-thailand/anytime/anytime/?sortBy=price",
    image: "/destinations/thailand.jpg",
    iataCode: "BKK",
    latitude: 13.7563,
    longitude: 100.5018,
    relatedDestinations: ["thajsko"],
  },
  {
    name: "Dubaj",
    slug: "dubaj",
    type: "city",
    title: "Letenky do Dubaje od 5 183 Kč | Burj Khalifa, Luxus",
    metaDescription: "Levné letenky do Dubaje. Burj Khalifa od 5 183 Kč. Luxus a mrakodrapy. Rezervujte online.",
    h1: "Letenky do Dubaje",
    h2: "Luxus a mrakodrapy",
    description: "Dubaj je futuristická metropole s nejvyšší budovou světa Burj Khalifa, luxusními hotely a obřími nákupními centry. Zažijte arabskou pohostinnost v moderním pojetí.",
    keywords: ["letenky dubaj", "letenky do dubaje", "levné letenky dubaj", "letenky burj khalifa"],
    searchVolume: 8600,
    difficulty: 63,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/dubaj?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=DXB",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/dubai-united-arab-emirates/anytime/anytime/?sortBy=price",
    image: "/destinations/dubai.jpg",
    iataCode: "DXB",
    latitude: 25.2048,
    longitude: 55.2708,
    relatedDestinations: ["sae"],
  },
  {
    name: "Hanoj",
    slug: "hanoj",
    type: "city",
    title: "Letenky do Hanoje od 7 990 Kč | Vietnamská Kuchyně",
    metaDescription: "Nejlevnější letenky do Hanoje. Vietnamská kuchyně od 7 990 Kč. Autentický Vietnam. Porovnání cen.",
    h1: "Letenky do Hanoje",
    h2: "Autentický Vietnam",
    description: "Hanoj je hlavní město Vietnamu s autentickou atmosférou, koloniální architekturou a vynikající kuchyní. Ideální výchozí bod pro objevování Vietnamu.",
    keywords: ["letenky hanoj", "letenky do hanoje", "levné letenky hanoj", "letenky vietnam"],
    searchVolume: 3200,
    difficulty: 47,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/hanoj?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=HAN",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/hanoi-vietnam/anytime/anytime/?sortBy=price",
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/89740521/PcIFUDsvFHLYFmbN.jpg",
    iataCode: "HAN",
    latitude: 21.0285,
    longitude: 105.8542,
    relatedDestinations: [],
  },
  {
    name: "Lisabon",
    slug: "lisabon",
    type: "city",
    title: "Letenky do Lisabonu od 890 Kč | Pastéis de Nata, Tramvaje",
    metaDescription: "Levné letenky do Lisabonu. Pastéis de Nata od 890 Kč. Město na sedmi pahorcích. Rezervujte online.",
    h1: "Letenky do Lisabonu",
    h2: "Město na sedmi pahorcích",
    description: "Lisabon je portugalská perla s historickými tramvajemi, azulejovými dlaždicemi a vynikajícími pastéis de nata. Zažijte fado hudbu a atlantickou atmosféru.",
    keywords: ["letenky lisabon", "letenky do lisabonu", "levné letenky lisabon"],
    searchVolume: 6400,
    difficulty: 57,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/lisabon?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=LIS",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/lisbon-portugal/anytime/anytime/?sortBy=price",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&h=600&fit=crop",
    iataCode: "LIS",
    latitude: 38.7223,
    longitude: -9.1393,
    relatedDestinations: [],
  },
  {
    name: "Havana",
    slug: "havana",
    type: "city",
    title: "Letenky do Havany od 11 990 Kč | Kubánská Atmosféra",
    metaDescription: "Nejlevnější letenky do Havany. Kubánská atmosféra od 11 990 Kč. Oldtimery a rum. Porovnání cen.",
    h1: "Letenky do Havany",
    h2: "Oldtimery a rum",
    description: "Havana je kubánská metropole zamrzlá v čase - barevné oldtimery, koloniální architektura, živá salsa hudba a vynikající rum. Zažijte karibskou atmosféru.",
    keywords: ["letenky havana", "letenky do havany", "levné letenky havana", "letenky kuba"],
    searchVolume: 2100,
    difficulty: 41,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/havana?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=HAV",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/havana-cuba/anytime/anytime/?sortBy=price",
    image: "https://images.unsplash.com/photo-1518544801976-3e159e50e5bb?w=800&h=600&fit=crop",
    iataCode: "HAV",
    latitude: 23.1136,
    longitude: -82.3666,
    relatedDestinations: [],
  },
  {
    name: "Amsterdam",
    slug: "amsterdam",
    type: "city",
    title: "Letenky do Amsterdamu od 1 150 Kč | Kanály, Muzea",
    metaDescription: "Levné letenky do Amsterdamu. Kanály od 1 150 Kč. Město kanálů a muzeí. Rezervujte online.",
    h1: "Letenky do Amsterdamu",
    h2: "Město kanálů a muzeí",
    description: "Amsterdam je nizozemská metropole s romantickými kanály, světoznámými muzei (Van Gogh, Rijksmuseum) a unikátní atmosférou. Ideální pro víkendový výlet.",
    keywords: ["letenky amsterdam", "letenky do amsterdamu", "levné letenky amsterdam"],
    searchVolume: 7900,
    difficulty: 60,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/amsterdam?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=AMS",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/amsterdam-netherlands/anytime/anytime/?sortBy=price",
    image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&h=600&fit=crop",
    iataCode: "AMS",
    latitude: 52.3676,
    longitude: 4.9041,
    relatedDestinations: [],
  },
  {
    name: "Malaga",
    slug: "malaga",
    type: "city",
    title: "Letenky do Malagy od 890 Kč | Costa del Sol, Pláže",
    metaDescription: "Nejlevnější letenky do Malagy. Costa del Sol od 890 Kč. Slunce a pláže. Porovnání cen.",
    h1: "Letenky do Malagy",
    h2: "Slunce a pláže",
    description: "Malaga je brána na Costa del Sol s nekonečnými plážemi, historickým centrem a vynikající andaluskou kuchyní. Ideální pro letní dovolenou.",
    keywords: ["letenky malaga", "letenky do malagy", "levné letenky malaga"],
    searchVolume: 4700,
    difficulty: 53,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/malaga?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=AGP",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/malaga-spain/anytime/anytime/?sortBy=price",
    image: "https://images.unsplash.com/photo-1562883676-8c7feb83f09b?w=800&h=600&fit=crop",
    iataCode: "AGP",
    latitude: 36.7213,
    longitude: -4.4214,
    relatedDestinations: ["spanelsko"],
  },
  {
    name: "Maledivy",
    slug: "maledivy",
    type: "city",
    title: "Letenky na Maledivy od 14 990 Kč | Tropický Ráj",
    metaDescription: "Levné letenky na Maledivy. Tropický ráj od 14 990 Kč. Dokonalé pláže a bílý písek. Rezervujte online.",
    h1: "Letenky na Maledivy",
    h2: "Dokonalé pláže a bílý písek",
    description: "Maledivy jsou synonymem pro luxusní dovolenou - tyrkysové laguny, bílé pláže, korálové útesy a overwater bungalovy. Zažijte tropický ráj.",
    keywords: ["letenky maledivy", "letenky na maledivy", "levné letenky maledivy"],
    searchVolume: 5200,
    difficulty: 55,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/male?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=MLE",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/male-maldives/anytime/anytime/?sortBy=price",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&h=600&fit=crop",
    iataCode: "MLE",
    latitude: 4.1755,
    longitude: 73.5093,
    relatedDestinations: [],
  },
  {
    name: "Miláno",
    slug: "milano",
    type: "city",
    title: "Letenky do Milána od 890 Kč | Móda, Duomo",
    metaDescription: "Nejlevnější letenky do Milána. Duomo od 890 Kč. Módní metropole. Porovnání cen.",
    h1: "Letenky do Milána",
    h2: "Módní metropole",
    description: "Miláno je italská módní metropole s ikonickým Duomem, operou La Scala a luxusními butiky. Zažijte italský styl a design.",
    keywords: ["letenky miláno", "letenky do milána", "levné letenky miláno"],
    searchVolume: 6100,
    difficulty: 56,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/milano?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=MXP",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/milan-italy/anytime/anytime/?sortBy=price",
    image: "https://images.unsplash.com/photo-1513581166391-887a96ddeafd?w=800&h=600&fit=crop",
    iataCode: "MXP",
    latitude: 45.4642,
    longitude: 9.1900,
    relatedDestinations: ["italie"],
  },
  {
    name: "Abu Dhabi",
    slug: "abu-dhabi",
    type: "city",
    title: "Letenky do Abu Dhabi od 5 490 Kč | Velká Mešita",
    metaDescription: "Levné letenky do Abu Dhabi. Velká mešita od 5 490 Kč. Luxus a kultura. Rezervujte online.",
    h1: "Letenky do Abu Dhabi",
    h2: "Luxus a kultura",
    description: "Abu Dhabi je hlavní město SAE s nádhernou Velkou mešitou, Louvre Abu Dhabi a luxusními hotely. Zažijte arabskou kulturu v moderním pojetí.",
    keywords: ["letenky abu dhabi", "letenky do abu dhabi", "levné letenky abu dhabi"],
    searchVolume: 3800,
    difficulty: 50,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/abu-dhabi?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=AUH",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/abu-dhabi-united-arab-emirates/anytime/anytime/?sortBy=price",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop",
    iataCode: "AUH",
    latitude: 24.4539,
    longitude: 54.3773,
    relatedDestinations: ["sae"],
  },
  {
    name: "Neapol",
    slug: "neapol",
    type: "city",
    title: "Letenky do Neapole od 790 Kč | Pizza, Vesuv",
    metaDescription: "Nejlevnější letenky do Neapole. Vesuv od 790 Kč. Autentická Itálie. Porovnání cen.",
    h1: "Letenky do Neapole",
    h2: "Autentická Itálie",
    description: "Neapol je kolébka pizzy s autentickou italskou atmosférou, sopkou Vesuv a Pompejemi. Zažijte pravou jižní Itálii.",
    keywords: ["letenky neapol", "letenky do neapole", "levné letenky neapol"],
    searchVolume: 2800,
    difficulty: 44,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/neapol?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=NAP",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/naples-italy/anytime/anytime/?sortBy=price",
    image: "https://images.unsplash.com/photo-1543429258-f9e39f3a8e3c?w=800&h=600&fit=crop",
    latitude: 40.8518,
    longitude: 14.2681,
    relatedDestinations: ["italie"],
  },
  {
    name: "Zadar",
    slug: "zadar",
    type: "city",
    title: "Letenky do Zadaru od 690 Kč | Chorvatské Pobřeží",
    metaDescription: "Levné letenky do Zadaru. Chorvatské pobřeží od 690 Kč. Krásné pláže. Rezervujte online.",
    h1: "Letenky do Zadaru",
    h2: "Krásné pláže",
    description: "Zadar je chorvatské město s unikátním Mořským varhanami, historickým centrem a krásnými plážemi. Ideální výchozí bod pro objevování Dalmácie.",
    keywords: ["letenky zadar", "letenky do zadaru", "levné letenky zadar"],
    searchVolume: 3100,
    difficulty: 46,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/zadar?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=ZAD",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/zadar-croatia/anytime/anytime/?sortBy=price",
    image: "https://images.unsplash.com/photo-1557555187-23d685287bc3?w=800&h=600&fit=crop",
    latitude: 44.1194,
    longitude: 15.2314,
    relatedDestinations: ["chorvatsko"],
  },
  {
    name: "Cancún",
    slug: "cancun",
    type: "city",
    title: "Letenky do Cancúnu od 10 990 Kč | Karibské Pláže",
    metaDescription: "Nejlevnější letenky do Cancúnu. Karibské pláže od 10 990 Kč. Mayské pyramidy. Porovnání cen.",
    h1: "Letenky do Cancúnu",
    h2: "Karibské pláže a mayské pyramidy",
    description: "Cancún je mexické letovisko s nejkrásnějšími karibskými plážemi, mayskými pyramidami a živým nočním životem. Ideální pro dovolenou snů.",
    keywords: ["letenky cancún", "letenky do cancúnu", "levné letenky cancún"],
    searchVolume: 4200,
    difficulty: 51,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/cancun?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=CUN",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/cancun-mexico/anytime/anytime/?sortBy=price",
    image: "https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=800&h=600&fit=crop",
    latitude: 21.1619,
    longitude: -86.8515,
    relatedDestinations: ["mexiko"],
  },
  {
    name: "Palma de Mallorca",
    slug: "palma-de-mallorca",
    type: "city",
    title: "Letenky do Palmy de Mallorca od 990 Kč | Baleárské Ostrovy",
    metaDescription: "Levné letenky do Palmy de Mallorca. Baleárské ostrovy od 990 Kč. Pláže a noční život. Rezervujte online.",
    h1: "Letenky do Palmy de Mallorca",
    h2: "Pláže a noční život",
    description: "Palma de Mallorca je hlavní město Baleárských ostrovů s krásnými plážemi, historickým centrem a živým nočním životem. Ideální pro letní dovolenou.",
    keywords: ["letenky palma de mallorca", "letenky mallorca", "levné letenky mallorca"],
    searchVolume: 5600,
    difficulty: 54,
    pelikanUrl: "https://www.pelikan.cz/akcni-letenky/praha/palma-de-mallorca?a_aid=levne-letenky&a_bid=7e4cf1c9&data[from]=PRG&data[to]=PMI",
    kiwiUrl: "https://www.kiwi.com/cz/search/results/letiste-vaclava-havla-praha-praha-cesko/palma-mallorca-spain/anytime/anytime/?sortBy=price",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop",
    latitude: 39.5696,
    longitude: 2.6502,
    relatedDestinations: ["spanelsko"],
  },
];
